### ISSUE TITLE
Crashes on HTC M8 after downloading first builds

### ISSUE THREAD

**Issue by ghost** [Naramsim/Aoe2-Stratega#3]
Once I installed the two suggested build orders the app kept crashing on startup (HTC M8).

```
    Build version: 1.6 
    Build date: 2016-05-10 15:13:18 
    Current date: 2016-05-10 12:22:13

    Stack trace:  
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ale.aoe2.stratega/com.ale.aoe2.stratega.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.trim()' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.    java:2411)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.    java:2474)
    at android.app.ActivityThread.access$800(ActivityThread.java:144)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1359)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:155)
    at android.app.ActivityThread.main(ActivityThread.java:5696)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(    ZygoteInit.java:1028)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
    Caused by: java.lang.NullPointerException: Attempt to invoke virtual     method 'java.lang.String java.lang.String.trim()' on a null object     reference
    at com.ale.aoe2.stratega.cg.<init>(Unknown Source)
    at com.ale.aoe2.stratega.w.I(Unknown Source)
    at com.ale.aoe2.stratega.w.a(Unknown Source)
    at android.support.v4.b.w.b(Unknown Source)
    at android.support.v4.b.ak.a(Unknown Source)
    at android.support.v4.b.ak.a(Unknown Source)
    at android.support.v4.b.m.run(Unknown Source)
    at android.support.v4.b.ak.e(Unknown Source)
    at android.support.v4.b.ag.n(Unknown Source)
    at android.support.v4.b.ab.onStart(Unknown Source)
    at android.app.Instrumentation.callActivityOnStart(Instrumentation.    java:1288)
    at android.app.Activity.performStart(Activity.java:5974)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.    java:2374)
    ... 10 more
```

**Comment by Naramsim** [comment]
Hi, first of all thanks for downloading the app.
The issue was caused by a strage behaviour of Proguard minification of code.
I've fixed the app, and soon on the play store there will be the 1.8 version which has the issue fixed.

Thanks for pointing it out
